# preload = /home/johann/Media/Pictures/wallpaper.webp
# wallpaper = , /home/johann/Media/Pictures/wallpaper.webp
wallpaper {
    monitor = 
    path = /home/johann/Media/Pictures/wallpaper.webp
    fit_mode = cover
}
